config/routes.rb
Rails.application.routes.draw do

  resources :join_table_items_orders
  resources :join_table_carts_items
  resources :orders
  resources :carts
  devise_for :users
  resources :users, only: [:show, :edit, :destroy]
  resources :items
  root to: 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

    validates :title, 
        presence: true, length: { in: 3..20 }
    validates :description, 
        presence: true, length: { minimum: 10 }
    validates :price, 
        presence: true, numericality: { greater_than: 0 }
  
    has_many :join_table_carts_items, dependent: :destroy
    has_many :carts, through: :join_table_carts_items
    has_many :join_items_orders, dependent: :destroy
    has_many :orders, through: :join_items_orders

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'layouts/banner' %>
<br>
  
<div class='containerfluid row ml-2 mr-2 d-flex justify-content-around gx-0 mb-5'>

  <% @items.each do |item| %>

    <div class="card m-4" style="width: 22rem;">
   <%= image_tag ("6.jpg") %>
      <div class="card-body">
        <h5 class="card-title"><%= item.title %></h5>
        <p class="card-text"><%= item.description %></p>
       
		<%= link_to "Show", item_path(item), class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>

<div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div style="height:70vh; display:flex; justify-content:space-around;margin-bottom:10vh;  ">
<div class="card" style="width: 40rem;">
<%= image_tag ("4.jpg") %>
<h6>@Copyright</h6>
 
  
</div>
<div class="card" style="width: 40rem;">

 
  <div class="card-body">
    <h3 class="card-title" style="display:flex; justify-content:center"><strong><%= @item.title %></strong></h3>
    </br>
    </br>
    <h4><strong>Description</strong></h4>
    <p class="card-text"><%= @item.description %></p>
    </br>
    </br>
    <h4><strong>Prix</strong></h4>
    <p class="card-text"><%= @item.price %>€</p>
    </br>
    </br>
  
    
  	<% if !!current_user %>
      <%= link_to "Add to cart", cart_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Add to cart", new_user_registration_path, class: "btn btn-primary" %>
	  <% end %>
  </div>
</div>
</div>