config/routes.rb
Rails.application.routes.draw do

  resources :join_table_items_orders
  resources :join_table_carts_items
  resources :orders
  resources :carts
  devise_for :users
  resources :users, only: [:show, :edit, :destroy]
  resources :items
  root to: 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/join_table_carts_item.rb
class JoinTableCartsItem < ApplicationRecord
    
    belongs_to :item
    belongs_to :cart

end

app/controllers/join_table_carts_items_controller.rb
class JoinTableCartsItemsController < ApplicationController
  before_action :set_join_table_carts_item, only: %i[ show edit update destroy ]

  # GET /join_table_carts_items or /join_table_carts_items.json
  def index
    @join_table_carts_items = JoinTableCartsItem.all
  end

  # GET /join_table_carts_items/1 or /join_table_carts_items/1.json
  def show
  end

  # GET /join_table_carts_items/new
  def new
    @join_table_carts_item = JoinTableCartsItem.new
  end

  # GET /join_table_carts_items/1/edit
  def edit
  end

  # POST /join_table_carts_items or /join_table_carts_items.json
  def create
    @join_table_carts_item = JoinTableCartsItem.new(join_table_carts_item_params)

    respond_to do |format|
      if @join_table_carts_item.save
        format.html { redirect_to @join_table_carts_item, notice: "Join table carts item was successfully created." }
        format.json { render :show, status: :created, location: @join_table_carts_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @join_table_carts_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /join_table_carts_items/1 or /join_table_carts_items/1.json
  def update
    respond_to do |format|
      if @join_table_carts_item.update(join_table_carts_item_params)
        format.html { redirect_to @join_table_carts_item, notice: "Join table carts item was successfully updated." }
        format.json { render :show, status: :ok, location: @join_table_carts_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @join_table_carts_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /join_table_carts_items/1 or /join_table_carts_items/1.json
  def destroy
    @join_table_carts_item.destroy
    respond_to do |format|
      format.html { redirect_to join_table_carts_items_url, notice: "Join table carts item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join_table_carts_item
      @join_table_carts_item = JoinTableCartsItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def join_table_carts_item_params
      params.fetch(:join_table_carts_item, {})
    end
end

app/helpers/join_table_carts_items_helper.rb
module JoinTableCartsItemsHelper
end

app/views/join_table_carts_items/_form.html.erb
<%= form_with(model: join_table_carts_item, local: true) do |form| %>
  <% if join_table_carts_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(join_table_carts_item.errors.count, "error") %> prohibited this join_table_carts_item from being saved:</h2>

      <ul>
      <% join_table_carts_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/join_table_carts_items/edit.html.erb
<h1>Editing Join Table Carts Item</h1>

<%= render 'form', join_table_carts_item: @join_table_carts_item %>

<%= link_to 'Show', @join_table_carts_item %> |
<%= link_to 'Back', join_table_carts_items_path %>

app/views/join_table_carts_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Join Table Carts Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @join_table_carts_items.each do |join_table_carts_item| %>
      <tr>
        <td><%= link_to 'Show', join_table_carts_item %></td>
        <td><%= link_to 'Edit', edit_join_table_carts_item_path(join_table_carts_item) %></td>
        <td><%= link_to 'Destroy', join_table_carts_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Join Table Carts Item', new_join_table_carts_item_path %>

app/views/join_table_carts_items/new.html.erb
<h1>New Join Table Carts Item</h1>

<%= render 'form', join_table_carts_item: @join_table_carts_item %>

<%= link_to 'Back', join_table_carts_items_path %>

app/views/join_table_carts_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_join_table_carts_item_path(@join_table_carts_item) %> |
<%= link_to 'Back', join_table_carts_items_path %>